import { notFound } from "next/navigation";
import DashboardShell from "@/components/DashboardShell";
import HostelActions from "@/components/HostelActions";
import { getHostel, getReviews } from "@/lib/api/hostel.api";
import Image from "next/image";

export default async function HostelPage({ params }: { params: Promise<{id:string}> }) {
    const { id } = await params; const [hostelResult, reviewResult] = await Promise.all([getHostel(id), getReviews(id)]); if (!hostelResult.success) notFound(); const h = hostelResult.data; const reviews = reviewResult.success ? reviewResult.data : [];
    return <DashboardShell><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><main><div className="relative h-80 overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-500 to-violet-600">{h.images[0] ? <Image src={h.images[0]} alt={h.name} fill priority unoptimized sizes="(max-width: 1024px) 100vw, 70vw" className="object-cover"/> : <div className="flex h-full items-center justify-center text-8xl">🏠</div>}</div><div className="mt-6 flex items-start justify-between"><div><p className="text-sm font-bold text-indigo-600">{h.city}</p><h1 className="text-3xl font-bold">{h.name}</h1><p className="mt-1 text-zinc-500">{h.address}</p></div><div className="text-right"><p className="text-2xl font-bold text-indigo-700">Rs {h.pricePerNight}</p><p className="text-xs text-zinc-500">per night</p></div></div><p className="mt-6 leading-7 text-zinc-600">{h.description}</p><div className="mt-6 flex flex-wrap gap-2">{h.amenities.map(a => <span key={a} className="rounded-full bg-zinc-100 px-3 py-2 text-sm">✓ {a}</span>)}</div><section className="mt-10"><h2 className="text-xl font-bold">Guest reviews <span className="text-amber-500">★ {h.rating.toFixed(1)}</span></h2><div className="mt-4 space-y-3">{reviews.map(r => <article key={r._id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><strong>{r.user.name}</strong><span className="text-amber-500">{"★".repeat(r.rating)}</span></div><p className="mt-2 text-zinc-600">{r.comment}</p></article>)}{!reviews.length && <p className="text-zinc-500">No reviews yet.</p>}</div></section></main><aside><div className="mb-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{h.availableBeds} beds currently available</div><HostelActions id={id}/></aside></div></DashboardShell>;
}
