import Link from "next/link";
import DashboardShell from "@/components/DashboardShell";
import { getDashboard } from "@/lib/api/hostel.api";

export default async function DashboardPage() {
    const result = await getDashboard(); const data = result.success ? result.data : { saved: 0, bookings: 0, reviews: 0, upcoming: [] };
    return <DashboardShell><section><div className="rounded-3xl bg-gradient-to-r from-indigo-700 to-violet-600 p-8 text-white"><p className="text-sm font-semibold uppercase tracking-widest text-indigo-200">Your travel hub</p><h1 className="mt-2 text-3xl font-bold">Ready for your next stay?</h1><p className="mt-2 max-w-xl text-indigo-100">Find affordable, trusted hostels and manage every trip in one place.</p><Link href="/hostels" className="mt-6 inline-block rounded-xl bg-white px-5 py-3 font-bold text-indigo-700">Explore hostels</Link></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Saved hostels",data.saved,"indigo"],["Bookings",data.bookings,"violet"],["Reviews",data.reviews,"emerald"]].map(([label,value,color]) => <div key={String(label)} className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><p className={`text-sm font-semibold text-${color}-600`}>{label}</p><p className="mt-2 text-4xl font-bold">{value}</p></div>)}</div>
    <div className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Upcoming stays</h2><Link href="/bookings" className="text-sm font-semibold text-indigo-600">View all</Link></div><div className="mt-4 grid gap-3">{data.upcoming.length ? data.upcoming.map(b => <Link href={`/hostels/${b.hostel._id}`} key={b._id} className="rounded-2xl border bg-white p-5"><strong>{b.hostel.name}</strong><p className="text-sm text-zinc-500">{new Date(b.checkIn).toLocaleDateString()} – {new Date(b.checkOut).toLocaleDateString()} · {b.guests} guest(s)</p></Link>) : <div className="rounded-2xl border border-dashed p-8 text-center text-zinc-500">No upcoming stays yet.</div>}</div></div></section></DashboardShell>;
}
